var g=void 0,k=!0,l=null,m=!1,n,aa=[];function ba(a){return function(){return aa[a].apply(this,arguments)}}var ca=ca||{},p=this;function da(a){a=a.split(".");for(var b=p,c;c=a.shift();)if(b[c]!=l)b=b[c];else return l;return b}function u(){}function ea(a){a.Q=function(){return a.Da?a.Da:a.Da=new a}}
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){return a!==g}function ha(a){return"array"==fa(a)}function ia(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function ja(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}function w(a){return a[ka]||(a[ka]=++la)}var ka="closure_uid_"+(1E9*Math.random()>>>0),la=0;function ma(a,b,c){return a.call.apply(a.bind,arguments)}
function na(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ma:na;return x.apply(l,arguments)}
function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var pa=Date.now||function(){return+new Date},qa=l;function ra(a,b){function c(){}c.prototype=b.prototype;a.va=b.prototype;a.prototype=new c};function y(a){return/^[\s\xa0]*$/.test(a==l?"":String(a))}function sa(a){if(!ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ua,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(va,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(wa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(xa,"&quot;"));return a}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ta=/[&<>\"]/;
function z(a){var b=0,c=String(ya).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");for(var d=Math.max(c.length,a.length),f=0;0==b&&f<d;f++){var e=c[f]||"",h=a[f]||"",q=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var s=q.exec(e)||["","",""],t=r.exec(h)||["","",""];if(0==s[0].length&&0==t[0].length)break;b=((0==s[1].length?0:parseInt(s[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==s[1].length?0:parseInt(s[1],10))>(0==t[1].length?
0:parseInt(t[1],10))?1:0)||((0==s[2].length)<(0==t[2].length)?-1:(0==s[2].length)>(0==t[2].length)?1:0)||(s[2]<t[2]?-1:s[2]>t[2]?1:0)}while(0==b)}return b}function za(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function Aa(a){var b=v(g)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};var A=Array.prototype,B=A.indexOf?function(a,b,c){return A.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(v(a))return!v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=A.forEach?function(a,b,c){A.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=v(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Da=A.filter?function(a,b,c){return A.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,h=v(a)?a.split(""):
a,q=0;q<d;q++)if(q in h){var r=h[q];b.call(c,r,q,a)&&(f[e++]=r)}return f};function Ea(a,b){var c={show:"unavailable",status:"",priority:0};if(a.reduce)return a.reduce(b,c);var d=c;Ca(a,function(c,e){d=b.call(g,d,c,e,a)});return d}function Fa(a){var b;a:{b=Ga;for(var c=a.length,d=v(a)?a.split(""):a,f=0;f<c;f++)if(f in d&&b.call(g,d[f],f,a)){b=f;break a}b=-1}return 0>b?l:v(a)?a.charAt(b):a[b]}function Ha(a,b){var c=B(a,b);0<=c&&A.splice.call(a,c,1)}
function Ia(a){return A.concat.apply(A,arguments)}function Ja(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ka(a,b,c){return 2>=arguments.length?A.slice.call(a,b):A.slice.call(a,b,c)};function La(a,b){for(var c in a)b.call(g,a[c],c,a)}function Ma(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Na(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Pa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Oa.length;e++)c=Oa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Qa(a){if("function"==typeof a.p)return a.p();if(v(a))return a.split("");if(ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ma(a)}function Ra(a){if("function"==typeof a.z)return a.z();if("function"!=typeof a.p){if(ia(a)||v(a)){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return Na(a)}}
function Sa(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ia(a)||v(a))Ca(a,b,c);else for(var d=Ra(a),f=Qa(a),e=f.length,h=0;h<e;h++)b.call(c,f[h],d&&d[h],a)};function Ta(a,b){this.u={};this.g=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Ta?(c=a.z(),d=a.p()):(c=Na(a),d=Ma(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}n=Ta.prototype;n.d=0;n.Ma=0;n.p=function(){Ua(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.u[this.g[b]]);return a};n.z=function(){Ua(this);return this.g.concat()};n.C=function(a){return Va(this.u,a)};
n.remove=function(a){return Va(this.u,a)?(delete this.u[a],this.d--,this.Ma++,this.g.length>2*this.d&&Ua(this),k):m};function Ua(a){if(a.d!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Va(a.u,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.d!=a.g.length){for(var f={},c=b=0;b<a.g.length;)d=a.g[b],Va(f,d)||(a.g[c++]=d,f[d]=1),b++;a.g.length=c}}n.get=function(a,b){return Va(this.u,a)?this.u[a]:b};n.set=function(a,b){Va(this.u,a)||(this.d++,this.g.push(a),this.Ma++);this.u[a]=b};n.B=function(){return new Ta(this)};
function Va(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Wa,Xa,Ya,Za;function $a(){return p.navigator?p.navigator.userAgent:l}Za=Ya=Xa=Wa=m;var ab;if(ab=$a()){var bb=p.navigator;Wa=0==ab.indexOf("Opera");Xa=!Wa&&-1!=ab.indexOf("MSIE");Ya=!Wa&&-1!=ab.indexOf("WebKit");Za=!Wa&&!Ya&&"Gecko"==bb.product}var cb=Wa,C=Xa,D=Za,E=Ya,db=p.navigator,eb=-1!=(db&&db.platform||"").indexOf("Mac");function fb(){var a=p.document;return a?a.documentMode:g}var ya;
a:{var gb="",hb;if(cb&&p.opera)var ib=p.opera.version,gb="function"==typeof ib?ib():ib;else if(D?hb=/rv\:([^\);]+)(\)|;)/:C?hb=/MSIE\s+([^\);]+)(\)|;)/:E&&(hb=/WebKit\/(\S+)/),hb)var jb=hb.exec($a()),gb=jb?jb[1]:"";if(C){var kb=fb();if(kb>parseFloat(gb)){ya=String(kb);break a}}ya=gb}var lb={};function F(a){return lb[a]||(lb[a]=0<=z(a))}var mb=p.document,nb=!mb||!C?g:fb()||("CSS1Compat"==mb.compatMode?parseInt(ya,10):5);var ob=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function pb(a,b){var c;if(a instanceof pb)this.n=ga(b)?b:a.n,qb(this,a.M),c=a.ka,G(this),this.ka=c,c=a.P,G(this),this.P=c,rb(this,a.ha),c=a.ga,G(this),this.ga=c,sb(this,a.r.B()),c=a.aa,G(this),this.aa=c;else if(a&&(c=String(a).match(ob))){this.n=!!b;qb(this,c[1]||"",k);var d=c[2]||"";G(this);this.ka=d?decodeURIComponent(d):"";d=c[3]||"";G(this);this.P=d?decodeURIComponent(d):"";rb(this,c[4]);d=c[5]||"";G(this);this.ga=d?decodeURIComponent(d):"";sb(this,c[6]||"",k);c=c[7]||"";G(this);this.aa=c?decodeURIComponent(c):
""}else this.n=!!b,this.r=new tb(l,0,this.n)}n=pb.prototype;n.M="";n.ka="";n.P="";n.ha=l;n.ga="";n.aa="";n.Ta=m;n.n=m;n.toString=function(){var a=[],b=this.M;b&&a.push(ub(b,vb),":");if(b=this.P){a.push("//");var c=this.ka;c&&a.push(ub(c,vb),"@");a.push(encodeURIComponent(String(b)));b=this.ha;b!=l&&a.push(":",String(b))}if(b=this.ga)this.P&&"/"!=b.charAt(0)&&a.push("/"),a.push(ub(b,"/"==b.charAt(0)?wb:xb));(b=this.r.toString())&&a.push("?",b);(b=this.aa)&&a.push("#",ub(b,yb));return a.join("")};
n.B=function(){return new pb(this)};function qb(a,b,c){G(a);a.M=c?b?decodeURIComponent(b):"":b;a.M&&(a.M=a.M.replace(/:$/,""))}function rb(a,b){G(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.ha=b}else a.ha=l}function sb(a,b,c){G(a);b instanceof tb?(a.r=b,a.r.ua(a.n)):(c||(b=ub(b,zb)),a.r=new tb(b,0,a.n))}function G(a){if(a.Ta)throw Error("Tried to modify a read-only Uri");}n.ua=function(a){this.n=a;this.r&&this.r.ua(a);return this};
function ub(a,b){return v(a)?encodeURI(a).replace(b,Ab):l}function Ab(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var vb=/[#\/\?@]/g,xb=/[\#\?:]/g,wb=/[\#\?]/g,zb=/[\#\?@]/g,yb=/#/g;function tb(a,b,c){this.m=a||l;this.n=!!c}
function I(a){if(!a.f&&(a.f=new Ta,a.d=0,a.m))for(var b=a.m.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=l,e=l;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=J(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}n=tb.prototype;n.f=l;n.d=l;n.add=function(a,b){I(this);this.m=l;a=J(this,a);var c=this.f.get(a);c||this.f.set(a,c=[]);c.push(b);this.d++;return this};
n.remove=function(a){I(this);a=J(this,a);return this.f.C(a)?(this.m=l,this.d-=this.f.get(a).length,this.f.remove(a)):m};n.C=function(a){I(this);a=J(this,a);return this.f.C(a)};n.z=function(){I(this);for(var a=this.f.p(),b=this.f.z(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};n.p=function(a){I(this);var b=[];if(a)this.C(a)&&(b=Ia(b,this.f.get(J(this,a))));else{a=this.f.p();for(var c=0;c<a.length;c++)b=Ia(b,a[c])}return b};
n.set=function(a,b){I(this);this.m=l;a=J(this,a);this.C(a)&&(this.d-=this.f.get(a).length);this.f.set(a,[b]);this.d++;return this};n.get=function(a,b){var c=a?this.p(a):[];return 0<c.length?String(c[0]):b};function Bb(a,b,c){a.remove(b);0<c.length&&(a.m=l,a.f.set(J(a,b),Ja(c)),a.d+=c.length)}
n.toString=function(){if(this.m)return this.m;if(!this.f)return"";for(var a=[],b=this.f.z(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.p(d),e=0;e<d.length;e++){var h=f;""!==d[e]&&(h+="="+encodeURIComponent(String(d[e])));a.push(h)}return this.m=a.join("&")};n.B=function(){var a=new tb;a.m=this.m;this.f&&(a.f=this.f.B(),a.d=this.d);return a};function J(a,b){var c=String(b);a.n&&(c=c.toLowerCase());return c}
n.ua=function(a){a&&!this.n&&(I(this),this.m=l,Sa(this.f,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),Bb(this,d,a))},this));this.n=a};function Cb(a){return Db(a||arguments.callee.caller,[])}
function Db(a,b){var c=[];if(0<=B(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Eb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Eb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Db(a.caller,b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Eb(a){if(Fb[a])return Fb[a];a=String(a);if(!Fb[a]){var b=/function ([^\(]+)/.exec(a);Fb[a]=b?b[1]:"[Anonymous]"}return Fb[a]}var Fb={};var Gb,Hb=!C||C&&9<=nb,Ib=!D&&!C||C&&C&&9<=nb||D&&F("1.9.1");C&&F("9");function Jb(a,b){var c;c=a.className;c=v(c)&&c.match(/\S+/g)||[];for(var d=Ka(arguments,1),f=c.length+d.length,e=c,h=0;h<d.length;h++)0<=B(e,d[h])||e.push(d[h]);a.className=c.join(" ");return c.length==f};function K(a,b){this.x=ga(a)?a:0;this.y=ga(b)?b:0}K.prototype.B=function(){return new K(this.x,this.y)};K.prototype.floor=ba(1);K.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function L(a){return v(a)?document.getElementById(a):a}function Kb(a,b){var c=b||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):Lb(a,b)}
function Lb(a,b){var c,d,f,e;c=document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var h=c.getElementsByClassName(a);return h}h=c.getElementsByTagName("*");if(a){e={};for(d=f=0;c=h[d];d++){var q=c.className;"function"==typeof q.split&&0<=B(q.split(/\s+/),a)&&(e[f++]=c)}e.length=f;return e}return h}
function Mb(a,b){La(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Nb?a.setAttribute(Nb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function M(a,b,c){var d=arguments,f=document,e=d[0],h=d[1];if(!Hb&&h&&(h.name||h.type)){e=["<",e];h.name&&e.push(' name="',sa(h.name),'"');if(h.type){e.push(' type="',sa(h.type),'"');var q={};Pa(q,h);delete q.type;h=q}e.push(">");e=e.join("")}e=f.createElement(e);h&&(v(h)?e.className=h:ha(h)?Jb.apply(l,[e].concat(h)):Mb(e,h));2<d.length&&Ob(f,e,d);return e}
function Ob(a,b,c){function d(c){c&&b.appendChild(v(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];ia(e)&&!(ja(e)&&0<e.nodeType)?Ca(Pb(e)?Ja(e):e,d):d(e)}}function Qb(a){return a&&a.parentNode?a.parentNode.removeChild(a):l}function N(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Rb(a){var b=L("msg");if("textContent"in b)b.textContent=a;else if(b.firstChild&&3==b.firstChild.nodeType){for(;b.lastChild!=b.firstChild;)b.removeChild(b.lastChild);b.firstChild.data=a}else{for(var c;c=b.firstChild;)b.removeChild(c);b.appendChild(N(b).createTextNode(String(a)))}}function Pb(a){if(a&&"number"==typeof a.length){if(ja(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==fa(a))return"function"==typeof a.item}return m}
function O(a){this.w=a||p.document||document}O.prototype.createElement=function(a){return this.w.createElement(a)};O.prototype.createTextNode=function(a){return this.w.createTextNode(String(a))};O.prototype.appendChild=function(a,b){a.appendChild(b)};O.prototype.Ba=function(a){return Ib&&a.children!=g?a.children:Da(a.childNodes,function(a){return 1==a.nodeType})};var Sb=!C||C&&9<=nb,Tb=C&&!F("9");!E||F("528");D&&F("1.9b")||C&&F("8")||cb&&F("9.5")||E&&F("528");D&&!F("8")||C&&F("9");function Ub(){0!=Vb&&(this.kb=Error().stack,Wb[w(this)]=this)}var Vb=0,Wb={};Ub.prototype.xa=m;Ub.prototype.J=function(){if(!this.xa&&(this.xa=k,this.D(),0!=Vb)){var a=w(this);delete Wb[a]}};Ub.prototype.D=function(){if(this.Ha)for(;this.Ha.length;)this.Ha.shift()()};function Xb(a,b){this.type=a;this.currentTarget=this.target=b}n=Xb.prototype;n.D=function(){};n.J=function(){};n.L=m;n.defaultPrevented=m;n.ia=k;n.preventDefault=function(){this.defaultPrevented=k;this.ia=m};function Yb(a){Yb[" "](a);return a}Yb[" "]=u;function Zb(a,b){a&&this.ca(a,b)}ra(Zb,Xb);n=Zb.prototype;n.target=l;n.relatedTarget=l;n.offsetX=0;n.offsetY=0;n.clientX=0;n.clientY=0;n.screenX=0;n.screenY=0;n.button=0;n.keyCode=0;n.charCode=0;n.ctrlKey=m;n.altKey=m;n.shiftKey=m;n.metaKey=m;n.Za=m;n.ya=l;
n.ca=function(a,b){var c=this.type=a.type;Xb.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(D){var f;a:{try{Yb(d.nodeName);f=k;break a}catch(e){}f=m}f||(d=l)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=E||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=E||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Za=eb?a.metaKey:a.ctrlKey;this.state=a.state;this.ya=a;a.defaultPrevented&&this.preventDefault();delete this.L};
n.preventDefault=function(){Zb.va.preventDefault.call(this);var a=this.ya;if(a.preventDefault)a.preventDefault();else if(a.returnValue=m,Tb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};n.D=function(){};var $b=0;function ac(){}n=ac.prototype;n.key=0;n.G=m;n.$=m;n.ca=function(a,b,c,d,f,e){if("function"==fa(a))this.Ea=k;else if(a&&a.handleEvent&&"function"==fa(a.handleEvent))this.Ea=m;else throw Error("Invalid listener argument");this.A=a;this.Ja=b;this.src=c;this.type=d;this.capture=!!f;this.handler=e;this.$=m;this.key=++$b;this.G=m};n.handleEvent=function(a){return this.Ea?this.A.call(this.handler||this.src,a):this.A.handleEvent.call(this.A,a)};var bc={},P={},Q={},cc={};function R(a,b,c,d,f){if(ha(b))for(var e=0;e<b.length;e++)R(a,b[e],c,d,f);else a=dc(a,b,c,m,d,f),bc[a.key]=a}
function dc(a,b,c,d,f,e){if(!b)throw Error("Invalid event type");f=!!f;var h=P;b in h||(h[b]={d:0,l:0});h=h[b];f in h||(h[f]={d:0,l:0},h.d++);var h=h[f],q=w(a),r;h.l++;if(h[q]){r=h[q];for(var s=0;s<r.length;s++)if(h=r[s],h.A==c&&h.handler==e){if(h.G)break;d||(r[s].$=m);return r[s]}}else r=h[q]=[],h.d++;s=ec();h=new ac;h.ca(c,s,a,b,f,e);h.$=d;s.src=a;s.A=h;r.push(h);Q[q]||(Q[q]=[]);Q[q].push(h);a.addEventListener?(a==p||!a.customEvent_)&&a.addEventListener(b,s,f):a.attachEvent(b in cc?cc[b]:cc[b]=
"on"+b,s);return h}function ec(){var a=fc,b=Sb?function(c){return a.call(b.src,b.A,c)}:function(c){c=a.call(b.src,b.A,c);if(!c)return c};return b}function gc(a,b,c,d,f){if(ha(b))for(var e=0;e<b.length;e++)gc(a,b[e],c,d,f);else a=dc(a,b,c,k,d,f),bc[a.key]=a}
function hc(a,b,c,d,f){if(ha(b))for(var e=0;e<b.length;e++)hc(a,b[e],c,d,f);else{d=!!d;a:{e=P;if(b in e&&(e=e[b],d in e&&(e=e[d],a=w(a),e[a]))){a=e[a];break a}a=l}if(a)for(e=0;e<a.length;e++)if(a[e].A==c&&a[e].capture==d&&a[e].handler==f){ic(a[e].key);break}}}
function ic(a){var b=bc[a];if(b&&!b.G){var c=b.src,d=b.type,f=b.Ja,e=b.capture;c.removeEventListener?(c==p||!c.customEvent_)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in cc?cc[d]:cc[d]="on"+d,f);c=w(c);Q[c]&&(f=Q[c],Ha(f,b),0==f.length&&delete Q[c]);b.G=k;if(b=P[d][e][c])b.Ga=k,jc(d,e,c,b);delete bc[a]}}
function jc(a,b,c,d){if(!d.ea&&d.Ga){for(var f=0,e=0;f<d.length;f++)d[f].G?d[f].Ja.src=l:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.Ga=m;0==e&&(delete P[a][b][c],P[a][b].d--,0==P[a][b].d&&(delete P[a][b],P[a].d--),0==P[a].d&&delete P[a])}}function kc(a){var b=0;if(a!=l){if(a=w(a),Q[a]){a=Q[a];for(var c=a.length-1;0<=c;c--)ic(a[c].key),b++}}else La(bc,function(a,c){ic(c);b++})}
function lc(a,b,c,d,f){var e=1;b=w(b);if(a[b]){var h=--a.l,q=a[b];q.ea?q.ea++:q.ea=1;try{for(var r=q.length,s=0;s<r;s++){var t=q[s];t&&!t.G&&(e&=mc(t,f)!==m)}}finally{a.l=Math.max(h,a.l),q.ea--,jc(c,d,b,q)}}return Boolean(e)}function mc(a,b){a.$&&ic(a.key);return a.handleEvent(b)}
function fc(a,b){if(a.G)return k;var c=a.type,d=P;if(!(c in d))return k;var d=d[c],f,e;if(!Sb){f=b||da("window.event");var h=k in d,q=m in d;if(h){if(0>f.keyCode||f.returnValue!=g)return k;a:{var r=m;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(s){r=k}if(r||f.returnValue==g)f.returnValue=k}}r=new Zb;r.ca(f,this);f=k;try{if(h){for(var t=[],Ba=r.currentTarget;Ba;Ba=Ba.parentNode)t.push(Ba);e=d[k];e.l=e.d;for(var H=t.length-1;!r.L&&0<=H&&e.l;H--)r.currentTarget=t[H],f&=lc(e,t[H],c,k,r);if(q){e=d[m];
e.l=e.d;for(H=0;!r.L&&H<t.length&&e.l;H++)r.currentTarget=t[H],f&=lc(e,t[H],c,m,r)}}else f=mc(a,r)}finally{t&&(t.length=0)}return f}c=new Zb(b,this);return f=mc(a,c)};function nc(a){this.w=a}var oc=/\s*;\s*/;n=nc.prototype;n.set=function(a,b,c,d,f,e){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');ga(c)||(c=-1);f=f?";domain="+f:"";d=d?";path="+d:"";e=e?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(pa()+1E3*c)).toUTCString();this.w.cookie=a+"="+b+f+d+c+e};
n.get=function(a,b){for(var c=a+"=",d=(this.w.cookie||"").split(oc),f=0,e;e=d[f];f++){if(0==e.lastIndexOf(c,0))return e.substr(c.length);if(e==a)return""}return b};n.remove=function(a,b,c){var d=this.C(a);this.set(a,"",0,b,c);return d};n.z=function(){return pc(this).keys};n.p=function(){return pc(this).gb};n.C=function(a){return ga(this.get(a))};
function pc(a){a=(a.w.cookie||"").split(oc);for(var b=[],c=[],d,f,e=0;f=a[e];e++)d=f.indexOf("="),-1==d?(b.push(""),c.push(f)):(b.push(f.substring(0,d)),c.push(f.substring(d+1)));return{keys:b,gb:c}};function qc(){Ub.call(this);this.lb={};this.jb=this}ra(qc,Ub);qc.prototype.customEvent_=k;n=qc.prototype;n.ra=l;n.addEventListener=function(a,b,c,d){R(this,a,b,c,d)};n.removeEventListener=function(a,b,c,d){hc(this,a,b,c,d)};
n.dispatchEvent=function(a){var b=a.type||a,c=P;if(b in c){if(v(a))a=new Xb(a,this);else if(a instanceof Xb)a.target=a.target||this;else{var d=a;a=new Xb(b,this);Pa(a,d)}var d=1,f,c=c[b],b=k in c,e;if(b){f=[];for(e=this;e;e=e.ra)f.push(e);e=c[k];e.l=e.d;for(var h=f.length-1;!a.L&&0<=h&&e.l;h--)a.currentTarget=f[h],d&=lc(e,f[h],a.type,k,a)&&a.ia!=m}if(m in c)if(e=c[m],e.l=e.d,b)for(h=0;!a.L&&h<f.length&&e.l;h++)a.currentTarget=f[h],d&=lc(e,f[h],a.type,m,a)&&a.ia!=m;else for(f=this;!a.L&&f&&e.l;f=f.ra)a.currentTarget=
f,d&=lc(e,f,a.type,m,a)&&a.ia!=m;a=Boolean(d)}else a=k;return a};n.D=function(){qc.va.D.call(this);kc(this);this.ra=l};function rc(a,b,c,d,f){this.reset(a,b,c,d,f)}rc.prototype.cb=0;rc.prototype.Aa=l;rc.prototype.za=l;var sc=0;rc.prototype.reset=function(a,b,c,d,f){this.cb="number"==typeof f?f:sc++;this.ob=d||pa();this.V=a;this.Wa=b;this.nb=c;delete this.Aa;delete this.za};rc.prototype.La=function(a){this.V=a};function S(a){this.Xa=a}S.prototype.fa=l;S.prototype.V=l;S.prototype.ma=l;S.prototype.R=l;function tc(a,b){this.name=a;this.value=b}tc.prototype.toString=function(){return this.name};var uc=new tc("SEVERE",1E3),vc=new tc("WARNING",900),wc=new tc("CONFIG",700),xc=new tc("FINE",500);n=S.prototype;n.addHandler=ba(2);n.getParent=function(){return this.fa};n.Ba=function(){this.ma||(this.ma={});return this.ma};n.La=function(a){this.V=a};function yc(a){return a.V?a.V:a.fa?yc(a.fa):l}
n.log=function(a,b,c){if(a.value>=yc(this).value){a=this.Na(a,b,c);b="log:"+a.Wa;p.console&&(p.console.timeStamp?p.console.timeStamp(b):p.console.markTimeline&&p.console.markTimeline(b));p.msWriteProfilerMark&&p.msWriteProfilerMark(b);for(b=this;b;){c=b;var d=a;if(c.R)for(var f=0,e=g;e=c.R[f];f++)e(d);b=b.getParent()}}};
n.Na=function(a,b,c){var d=new rc(a,String(b),this.Xa);if(c){d.Aa=c;var f;var e=arguments.callee.caller;try{var h;var q=da("window.location.href");if(v(c))h={message:c,name:"Unknown error",lineNumber:"Not available",fileName:q,stack:"Not available"};else{var r,s,t=m;try{r=c.lineNumber||c.mb||"Not available"}catch(Ba){r="Not available",t=k}try{s=c.fileName||c.filename||c.sourceURL||p.$googDebugFname||q}catch(H){s="Not available",t=k}h=t||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,
lineNumber:r,fileName:s,stack:c.stack||"Not available"}:c}f="Message: "+sa(h.message)+'\nUrl: <a href="view-source:'+h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+sa(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+sa(Cb(e)+"-> ")}catch(ud){f="Exception trying to expose exception! You win, we lose. "+ud}d.za=f}return d};function T(a,b){a.log(xc,b,g)}var zc={},Ac=l;
function Bc(a){Ac||(Ac=new S(""),zc[""]=Ac,Ac.La(wc));var b;if(!(b=zc[a])){b=new S(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Bc(a.substr(0,c));c.Ba()[d]=b;b.fa=c;zc[a]=b}return b};function Cc(){}Cc.prototype.Z=l;var Dc;function Ec(){}ra(Ec,Cc);function Fc(a){return(a=Gc(a))?new ActiveXObject(a):new XMLHttpRequest}function Hc(a){var b={};Gc(a)&&(b[0]=k,b[1]=k);return b}
function Gc(a){if(!a.Ca&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Ca=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Ca}Dc=new Ec;function U(a){qc.call(this);this.headers=new Ta;this.N=a||l}ra(U,qc);U.prototype.k=Bc("goog.net.XhrIo");var Ic=/^https?$/i,Jc=[];function Kc(a){a.J();Ha(Jc,a)}n=U.prototype;n.v=m;n.e=l;n.la=l;n.da="";n.Fa="";n.T=0;n.U="";n.oa=m;n.ba=m;n.qa=m;n.F=m;n.ja=0;n.H=l;n.Ka="";n.hb=m;
n.send=function(a,b,c,d){if(this.e)throw Error("[goog.net.XhrIo] Object is active with another request="+this.da+"; newUri="+a);b=b?b.toUpperCase():"GET";this.da=a;this.U="";this.T=0;this.Fa=b;this.oa=m;this.v=k;this.e=this.N?Fc(this.N):Fc(Dc);this.la=this.N?this.N.Z||(this.N.Z=Hc(this.N)):Dc.Z||(Dc.Z=Hc(Dc));this.e.onreadystatechange=x(this.Ia,this);try{T(this.k,V(this,"Opening Xhr")),this.qa=k,this.e.open(b,a,k),this.qa=m}catch(f){T(this.k,V(this,"Error opening Xhr: "+f.message));Lc(this,f);return}a=
c||"";var e=this.headers.B();d&&Sa(d,function(a,b){e.set(b,a)});d=Fa(e.z());c=p.FormData&&a instanceof p.FormData;"POST"==b&&(!d&&!c)&&e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");Sa(e,function(a,b){this.e.setRequestHeader(b,a)},this);this.Ka&&(this.e.responseType=this.Ka);"withCredentials"in this.e&&(this.e.withCredentials=this.hb);try{this.H&&(p.clearTimeout(this.H),this.H=l),0<this.ja&&(T(this.k,V(this,"Will abort after "+this.ja+"ms if incomplete")),this.H=p.setTimeout(x(this.eb,
this),this.ja)),T(this.k,V(this,"Sending request")),this.ba=k,this.e.send(a),this.ba=m}catch(h){T(this.k,V(this,"Send error: "+h.message)),Lc(this,h)}};function Ga(a){return"content-type"==a.toLowerCase()}n.eb=function(){"undefined"!=typeof ca&&this.e&&(this.U="Timed out after "+this.ja+"ms, aborting",this.T=8,T(this.k,V(this,this.U)),this.dispatchEvent("timeout"),this.abort(8))};function Lc(a,b){a.v=m;a.e&&(a.F=k,a.e.abort(),a.F=m);a.U=b;a.T=5;Mc(a);Nc(a)}
function Mc(a){a.oa||(a.oa=k,a.dispatchEvent("complete"),a.dispatchEvent("error"))}n.abort=function(a){this.e&&this.v&&(T(this.k,V(this,"Aborting")),this.v=m,this.F=k,this.e.abort(),this.F=m,this.T=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Nc(this))};n.D=function(){this.e&&(this.v&&(this.v=m,this.F=k,this.e.abort(),this.F=m),Nc(this,k));U.va.D.call(this)};n.Ia=function(){!this.qa&&!this.ba&&!this.F?this.Ya():Oc(this)};n.Ya=function(){Oc(this)};
function Oc(a){if(a.v&&"undefined"!=typeof ca)if(a.la[1]&&4==Pc(a)&&2==Qc(a))T(a.k,V(a,"Local request error detected and ignored"));else if(a.ba&&4==Pc(a))p.setTimeout(x(a.Ia,a),0);else if(a.dispatchEvent("readystatechange"),4==Pc(a)){T(a.k,V(a,"Request complete"));a.v=m;try{if(Rc(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{a.T=6;var b;try{b=2<Pc(a)?a.e.statusText:""}catch(c){T(a.k,"Can not get status: "+c.message),b=""}a.U=b+" ["+Qc(a)+"]";Mc(a)}}finally{Nc(a)}}}
function Nc(a,b){if(a.e){var c=a.e,d=a.la[0]?u:l;a.e=l;a.la=l;a.H&&(p.clearTimeout(a.H),a.H=l);b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(f){a.k.log(uc,"Problem encountered resetting onreadystatechange: "+f.message,g)}}}
function Rc(a){var b=Qc(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=k;break a;default:c=m}if(!c){if(b=0===b)a=String(a.da).match(ob)[1]||l,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!Ic.test(a?a.toLowerCase():"");c=b}return c}function Pc(a){return a.e?a.e.readyState:0}function Qc(a){try{return 2<Pc(a)?a.e.status:-1}catch(b){return a.k.log(vc,"Can not get status: "+b.message,g),-1}}
function V(a,b){return b+" ["+a.Fa+" "+a.da+" "+Qc(a)+"]"};function Sc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}Sc.prototype.B=function(){return new Sc(this.top,this.right,this.bottom,this.left)};Sc.prototype.floor=ba(0);Sc.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function Tc(a,b){v(b)?Uc(a,g,b):La(b,oa(Uc,a))}function Uc(a,b,c){var d;a:if(d=za(c),a.style[d]===g&&(c=(E?"Webkit":D?"Moz":C?"ms":cb?"O":l)+Aa(c),a.style[c]!==g)){d=c;break a}d&&(a.style[d]=b)}function Vc(a,b){var c=N(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,l))?c[b]||c.getPropertyValue(b)||"":""}function Wc(a){return Vc(a,"position")||(a.currentStyle?a.currentStyle.position:l)||a.style&&a.style.position}
function Xc(a){if(C&&!(C&&8<=nb))return a.offsetParent;var b=N(a),c=Wc(a),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Wc(a),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return l}
function Yc(a,b){var c;c=Zc(a);var d=Zc(b),f;if(C){var e=$c(b,"borderLeft");f=$c(b,"borderRight");var h=$c(b,"borderTop"),q=$c(b,"borderBottom");f=new Sc(h,f,q,e)}else e=Vc(b,"borderLeftWidth"),f=Vc(b,"borderRightWidth"),h=Vc(b,"borderTopWidth"),q=Vc(b,"borderBottomWidth"),f=new Sc(parseFloat(h),parseFloat(f),parseFloat(q),parseFloat(e));e=c.x-d.x-f.left;c=c.y-d.y-f.top;d=b.clientHeight-a.offsetHeight;f=b.scrollLeft;h=b.scrollTop;f+=Math.min(e,Math.max(e-(b.clientWidth-a.offsetWidth),0));h+=Math.min(c,
Math.max(c-d,0));c=new K(f,h);b.scrollLeft=c.x;b.scrollTop=c.y}
function Zc(a){var b,c=N(a),d=Wc(a),f=D&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),e=new K(0,0),h;b=c?N(c):document;if(h=C)if(h=!(C&&9<=nb))h="CSS1Compat"!=(b?new O(N(b)):Gb||(Gb=new O)).w.compatMode;h=h?b.body:b.documentElement;if(a==h)return e;if(a.getBoundingClientRect)b=a.getBoundingClientRect(),C&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop),
a=(c?new O(N(c)):Gb||(Gb=new O)).w,c=!E&&"CSS1Compat"==a.compatMode?a.documentElement:a.body,a=a.parentWindow||a.defaultView,c=C&&F("10")&&a.pageYOffset!=c.scrollTop?new K(c.scrollLeft,c.scrollTop):new K(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop),e.x=b.left+c.x,e.y=b.top+c.y;else if(c.getBoxObjectFor&&!f)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(h),e.x=b.screenX-c.screenX,e.y=b.screenY-c.screenY;else{b=a;do{e.x+=b.offsetLeft;e.y+=b.offsetTop;b!=a&&(e.x+=b.clientLeft||0,e.y+=b.clientTop||
0);if(E&&"fixed"==Wc(b)){e.x+=c.body.scrollLeft;e.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(cb||E&&"absolute"==d)e.y-=c.body.offsetTop;for(b=a;(b=Xc(b))&&b!=c.body&&b!=h;)if(e.x-=b.scrollLeft,!cb||"TR"!=b.tagName)e.y-=b.scrollTop}return e}function ad(a){"number"==typeof a&&(a=Math.round(a)+"px");return a}function bd(){var a=document.documentElement.style;"opacity"in a?a.opacity=0.33:"MozOpacity"in a?a.MozOpacity=0.33:"filter"in a&&(a.filter=0.33===""?"":"alpha(opacity=33)")}
var cd={thin:2,medium:4,thick:6};function $c(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:l))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:l,d;if(c in cd)d=cd[c];else if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var f=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=f;d=c}return d};var W={":cat:":"cat.gif",":dog:":"dog.gif","@-\\)":"alien.gif","8-\\]":"ogre.gif","\\|:-\\)":"rambo.gif",":#\\(":"hurt.gif","#-\\(":"dead.gif",":dragon:":"dragon.gif",":home:":"house.gif",":apple:":"apple.gif",":glasses:":"glasses.gif",":mushroom:":"mushroom.gif",":world:":"globe.gif",":syringe:":"needle.gif",":carrot:":"carrot.gif",":cherry:":"cherry.gif",":cobra:":"cobra.gif",":dinosaur:":"dinosaur.gif",":drink:":"drink.gif",":fish:":"fish.gif",":graduate:":"graduate.gif",":death:":"grimreaper.gif",
":hammer:":"hammer.gif",":helicopter:":"helicopter.gif",":skull:":"skull.gif",":speaker:":"speaker.gif",":p":"ditsy.gif",":god:":"trinity_glowing.gif",":water:":"water_molecule.gif",">:D":"laugh.gif",":o\\)":"cheerful.gif",":\\)":"smiley.gif","8-D":"cheeky.gif",":\\*\\)":"embarrassed.gif","B-\\)":"cool.gif","B-\\|":"calm.gif",":-!":"smoker.gif","\\|-\\)":"bandit.gif","P-\\)":"pirate.gif",":-\\)>":"old-man.gif","\\[:\\|\\]":"ninja.gif",":-\\[\\]":"gasmask.gif","3-\\|\\{":"sleeping.gif","8-\\/":"paranoid.gif",
"\\?-\\|":"ponder.gif",":-S":"nervous.gif","8-s":"confused.gif","8-\\|":"tired.gif","8-\\[":"bored.gif","8-\\(":"disappointed.gif",":-<":"sad.gif",">:-D":"evil.gif",">:-\\|":"angry.gif",">:-\\)":"devious.gif",":D":"grin.gif","8\\)":"classic.gif",":-\\]":"square-eyed.gif","\\|\\|-\\)":"cross-eyed.gif","8-\\)":"foureyes.gif"};W["o-\\)"]=W["O-\\)"]="cyclops.gif";W["o-\\]"]=W["O-\\]"]="robot.gif";W["O:-\\)"]=W["o:-\\)"]=W["o:\\)"]=W["O:\\)"]="angel.gif";W["\\(6\\)"]=W[":devil:"]="devil.gif";
W["\\(y\\)"]=W["\\(Y\\)"]=W[":yes:"]="thumbup.gif";W["\\(n\\)"]=W["\\(N\\)"]=W[":no:"]="thumbdown.gif";W[":heart:"]=W["\\(l\\)"]=W["\\(L\\)"]=W["\\(u\\)"]=W["\\(U\\)"]=W[":bheart:"]="heart.gif";W["\\(z\\)"]=W["\\(Z\\)"]=W[":man:"]="person.gif";W["\\(e\\)"]=W["\\(E\\)"]=W[":letter:"]="letter.gif";W[":coffee:"]=W["\\(c\\)"]=W["\\(C\\)"]="coffee.gif";W["\\(i\\)"]=W["\\(I\\)"]=W[":lamp:"]=W[":jabber:"]="bulb.gif";W["\\}\\{"]=W[":bat:"]="bat.gif";W["\\(t\\)"]=W["\\(T\\)"]=W[":phone:"]="phone.gif";
W["\\(p\\)"]=W["\\(P\\)"]=W[":photo:"]="camera.gif";W["\\(b\\)"]=W["\\(B\\)"]=W[":beer:"]="beer.gif";W[":wine:"]=W[":cocktail:"]=W["\\(d\\)"]=W["\\(D\\)"]="cocktail.gif";W["\\(8\\)"]=W[":note:"]=W[":music:"]="music.gif";W[":tux:"]=W[":linux:"]="penguin.gif";W[":tv:"]=W[":television:"]="tv.gif";W[":pill:"]=W["\\(E\\)"]=W["\\(e\\)"]="pill.png";W[":\\)"]=W[":-\\)"]="smile.gif";W["\\(:"]=W["\\(-:"]="spin.gif";W[";\\)"]=W[";-\\)"]=W["\\(;"]=W["\\(-;"]="wink.gif";W[":\\|"]=W[":-\\|"]="normal.gif";
W[":-\\\\"]=W[":\\\\"]=W[":\\/"]=W[":-\\/"]="ermm.gif";W[":S"]=W[":s"]=W[":-S"]=W[":-s"]="puzzled.gif";W[":\\("]=W[":-\\("]=W["\\):"]=W["\\)-:"]="depressed.gif";W[":'\\("]=W[":'-\\("]="cry.gif";W[":X"]=W[":x"]="speechless.gif";W[":o"]=W[">:-o"]="mad.gif";W[":-o"]=W[":O"]=W[":-O"]="surprised.gif";W["%\\)"]=W["%-\\)"]="evolved.gif";W[":D"]=W[":-d"]=W[":d"]=W[":-D"]="silly.gif";W[":-0"]=W[":-O"]="shocked.gif";W[":0"]=W[":O"]="scared.gif";W[":-P"]=W[":-p"]="lick.gif";W[":-\\)\\}"]=W[":-\\)\\{"]="beard.gif";
W[":-\\["]=W[":\\["]="vampire.gif";W["x-\\)"]=W["X-\\)"]="knocked-out.gif";function X(a){var b=p.messages||{},c=b.domain||"widget";b&&(b=b.locale_data);b&&(b=b[c]);b&&(b=b[a]);return b&&2<=b.length?b[1]:a};window.SM2_DEFER=k;
function Y(){if(C&&0>z("8.0")){var a=function(){var a=L("layout"),b=L("recv"),c=a.offsetWidth,a=a.offsetHeight;20<=c&&(b.style.width=ad(c));b.style.height=ad(a)};a();setTimeout(a,500);R(window,"resize",a)}if(D&&0>z("1.8")||C&&0>z("6.0")||cb&&0>z("8.0")||E&&0>z("416.11"))bd(),dd(this,"Your browser is not supported for chat.");else{ed(this);fd(this);gd(this);if(this.sa||window.parent===window)if(a=L("popout"))a.style.display="none";if(this.sa&&window.opener){a=L("recv");try{a.innerHTML=window.opener.document.getElementById("recv").innerHTML,
Ca(Kb("status",a),Qb),a.scrollTop=a.scrollHeight,window.jabber_resources=window.opener.jabber_resources,hd(this,window.jabber_resources),window.opener.vCard&&(window.vCard=window.opener.vCard)}catch(b){}a.scrollTop=a.scrollHeight}R(window,"unload",x(this.ta,this));if(0<=this.i.indexOf("@chat.")){if(a=L("file"))a.style.display="";if(a=L("mail"))a.style.display=""}this.q=(new nc(document)).get("libraryh3lp_jid")||l;this.W=[];this.na();id(this);try{window.opener&&window.opener.jid&&window.opener.sid&&
window.opener.rid?jd(this):this.O()}catch(c){this.O()}}}ea(Y);n=Y.prototype;n.o=l;n.pa=m;n.S=l;n.s=m;n.sa=m;n.j=l;n.loaded=m;n.Y=m;n.I=m;n.ta=function(){!this.pa&&this.j&&(this.j.abort(),this.j.J(),this.j=l)};function ed(a){var b=p.settings.identity,c=p.settings.sounds;y(b)||(a.S=b);y(c)||(a.s="true"===c||"1"===c)}
function fd(a){var b;b=(new pb(window.location.href)).r;var c=b.get("follow","false"),d=b.get("popout","false"),f=b.get("sound","false"),e=b.get("sounds",a.s?"true":"false");a.S=b.get("identity",a.S);a.pa="true"===c||"1"===c;a.sa="true"===d||"1"===d;a.s="true"===e||"1"===e||"true"===f||"1"===f;b=window.location.href.match(/[^/]+@(chat\.)?([^/?#]+)/);a.i=b[0];a.domain=b[2]}function kd(a){a.I?(a=L("recv"),Ca(Kb("status",a),Qb),a.scrollTop=a.scrollHeight):Rb("")}
function dd(a,b){kd(a);if(a.I){var c=L("recv"),d=M("div",l,M("span",{"class":"status"},b));c.appendChild(d);Yc(d,c)}else Rb(b)}function ld(a,b){if(y(b.status))if(y(b.show)||"unavailable"===b.show)dd(a,X("Chat is offline."));else{if(!a.I){var c="Chat is offline.";switch(b.show){case "chat":case "available":c="Type here to chat. Press ENTER to send.";break;case "dnd":c="Chat is busy.";break;case "away":case "xa":c="Chat is away."}dd(a,X(c))}}else dd(a,b.status)}
function md(a){var b=L("presence"),c=nd(b.src,"?").split("/"),d=c.length-2;c[4]!==a&&(b.src=["/presence/image",c[d],a].join("/"),b.setAttribute("alt","Chat is "+a))}function hd(a,b){var c=od(b);md(c.show||"unavailable");ld(a,c)}var pd="chat available dnd away xa unavailable".split(" ");function od(a){return Ea(a,function(a,c){var d=B(pd,a.show),f=B(pd,c.show);return f<d||f===d&&c.priority>a.priority?c:a})}n=Y.prototype;
n.O=function(){if(!this.I){var a=this.i.split("@"),a=new pb(["/presence/jid",a[0],a[1],"js"].join("/")),b=a.r;p.jabber_client_id&&(!C||0<=z("8.0"))&&b.set("client_id",p.jabber_client_id);b.set("_",pa());this.j&&(this.j.abort(),this.j.J(),this.j=l);this.j=new U;this.j.addEventListener("complete",function(a){a=a.target;if(Rc(a)){var b;try{b=a.e?a.e.responseText:""}catch(f){T(a.k,"Can not get responseText: "+f.message),b=""}if(p.execScript)p.execScript(b,"JavaScript");else if(p.eval)if(qa==l&&(p.eval("var _et_ = 1;"),
"undefined"!=typeof p._et_?(delete p._et_,qa=k):qa=m),qa)p.eval(b);else{a=p.document;var e=a.createElement("script");e.type="text/javascript";e.defer=m;e.appendChild(a.createTextNode(b));a.body.appendChild(e);a.body.removeChild(e)}else throw Error("goog.globalEval not available");hd(this,p.jabber_resources);!C||0<=z("8.0")?this.O():setTimeout(x(this.O,this),3E4)}else md("unavailable"),dd(this,X("Chat is offline.")),setTimeout(x(this.O,this),3E4)},m,this);this.j.send(a)}};
function gd(a){var b,c=(b=L("sounds"))||document,d=l;(b=(d=c.querySelectorAll&&c.querySelector?c.querySelector(".sprite"):Kb("sprite",b)[0])||l)&&(a.s?Tc(b,{backgroundPosition:"-10px 0px",width:"18px"}):Tc(b,{backgroundPosition:"0px 0px",width:"10px"}))}function qd(a){var b=document.createElement("script");b.type="text/javascript";b.src=a;b.setAttribute("async","true");document.documentElement.appendChild(b)}
function jd(a){a.loaded||(qd("https://d1aaqh87bn7fin.cloudfront.net/chat_2013042701.js"),a.loaded=k,a.s&&!a.Y&&setTimeout(function(){qd("https://d1aaqh87bn7fin.cloudfront.net/sound_2013042701.js")},1E3))}n.na=function(){var a=L("msg");gc(a,"click",function(){a.value="";jd(this)},m,this);gc(a,"focus",function(){a.value="";jd(this)},m,this);gc(a,"keydown",function(){this.I=k},m,this);R(a,"keypress",function(b){if(13===b.keyCode||10===b.keyCode)this.X(a.value),a.value="",b.preventDefault()},m,this)};
n.X=function(a){this.o==l||0<this.W.length?this.W.push(a):this.o&&this.o.X(a);rd(this,a,X("me"),"me")};
function rd(a,b,c,d){if(!y(b)){var f=L("recv");d=M("div",l,M("span",{"class":d},a.timestamp()," ",nd(c,"@"))," ");var e=d.innerHTML,h;b=b.replace(/  /g," &#160;").replace(/(\r\n|\r|\n)/g,"<br>");for(h in W)if(W.hasOwnProperty(h)){var q=RegExp("(^|\\s)"+h+"($|\\s)","g");b.match(q)&&(b=b.replace(q,'&nbsp;<img src="/emoticons/rythmbox/'+W[h]+'"/>'))}h=b.replace(/\b(https?:\/\/\S+)/gi,'<a href="$1" onclick="return libraryh3lp.openLink(this);">$1</a>').replace(/\b(\w+\@\S+\.\S+)/g,'<a href="mailto:$1">$1</a>').replace(/\b\*([^\*\r\n]+)\*/g,
"<b>$1</b>").replace(/\b\_([^\*\r\n]+)\_/g,"<em>$1</em>");d.innerHTML=e+h;f.appendChild(d);Yc(d,f);"me"!==c&&a.s&&a.Y&&sd()}}n.timestamp=function(){var a=new Date,b=a.getHours(),a=a.getMinutes();return""+(12<b?b-12:b)+":"+(9<a?a:"0"+a)};function nd(a,b){var c=a.indexOf(b);return 0<=c?a.substr(0,c):a}function id(a){var b={file:a.ab,mail:a.Va,popout:a.$a,sounds:a.fb,"send-line":a.bb},c;for(c in b)if(b.hasOwnProperty(c)){var d=L(c);d&&R(d,"click",b[c],m,a)}}
n.ab=function(){var a=L("recv"),b=M("form",{target:"filetarget",method:"post",action:"/2011-12-03/file/"+encodeURIComponent(this.i.replace(/@chat.*/,""))+"/"+encodeURIComponent(nd(this.q||"","/"))},M("hr"),X("Send file")+": ",M("input",{type:"file",name:"file"}),M("input",{type:"submit",value:X("Send"),onclick:'this.form.style.display = "none";'}),M("hr"));b.setAttribute("enctype","multipart/form-data");a.appendChild(b);Yc(b,a);return m};
n.Va=function(){var a=prompt(X("Send transcript to:"),"");if(y(a))return m;var b="/2011-12-03/mail/"+encodeURIComponent(this.i.replace(/@chat.*/,""))+"/"+encodeURIComponent(nd(this.q||"","/")),c={email:a,tz:(new Date).getTimezoneOffset()},a=Ra(c);if("undefined"==typeof a)throw Error("Keys are undefined");for(var d=new tb(l,0,g),c=Qa(c),f=0;f<a.length;f++){var e=a[f],h=c[f];ha(h)?Bb(d,e,h):d.add(e,h)}a=d.toString();d=new U;Jc.push(d);u&&R(d,"complete",u);R(d,"ready",oa(Kc,d));d.send(b,"POST",a,g);
return m};n.$a=function(){var a=window.innerWidth||document.documentElement.offsetWidth,b=window.innerHeight||document.documentElement.offsetHeight,c=new pb(location.href),d=c.r;d.set("popout","1");d.set("sounds",this.s?"1":"0");this.j&&(this.j.abort(),this.j.J(),this.j=l);md("unavailable");bd();this.o&&this.o.b&&(window.jid=this.o.b.jid,window.sid=this.o.b.sid,window.rid=this.o.b.rid,this.o.b.connected=m,this.o.b=l);window.open(c.toString(),"chat","resizable=1,width="+a+",height="+b);return m};
n.fb=function(a){this.s=!this.s;gd(this);this.s&&this.Y&&sd();a.preventDefault();this.Y||qd("https://d1aaqh87bn7fin.cloudfront.net/sound_2013042701.js");return m};n.bb=function(a){var b=L("msg");this.X(b.value);b.value="";a.preventDefault();return m};var td=["libraryh3lp"],Z=p;!(td[0]in Z)&&Z.execScript&&Z.execScript("var "+td[0]);for(var vd;td.length&&(vd=td.shift());)!td.length&&ga(Y)?Z[vd]=Y:Z=Z[vd]?Z[vd]:Z[vd]={};
Y.openLink=function(a){try{if(window.parent&&window.parent.location.host==window.location.host&&window.parent.openLink)return window.parent.openLink(a.href),m}catch(b){}window.open(a.href);return m};Y.Q();
